version: '3.10'


services:
  web:
    build: .
    command: python /pro/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/pro
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: